kind: pipeline
name: default

steps:
- name: Pre-config
  image: mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
  commands:
    - dotnet restore
- name: Build .NET
  image: mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
  commands:
    - dotnet publish -c Release -o out
