kind: pipeline
name: default

steps:
- name: Pre-config
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  commands:
    - dnu restore
- name: Build .NET
  image: microsoft/aspnet:1.0.0-rc1-update1-coreclr
  commands:
    - dnu build
